### ISSUE TITLE
Calculate detection AUROC from anomaly map

### ISSUE THREAD

**Issue by Howeng98** [gudovskiy/cflow-ad#29]
Is it possible to get the detection performance from the anomaly map (segmentation)? I mean like the way that get the top k highest anomaly score in the anomaly map and calculate the mean of them as the threshold for decide as anomaly or not.

Is there any misunderstanding or something that I miss about this kind of way to calculate detection performance instead of calculate with label (1,0) ?

Because I observe that you have a better performance in segmentation than the detection in this model
maybe your model is flow-based (generative-based) so it have a better behavior in pixel level?

**Comment by gudovskiy** [comment]
Hi @Howeng98 in this paper, I didn't really prioritize detection performance. That's why I simply take max of [2D anomaly map](https://github.com/gudovskiy/cflow-ad/blob/4d6ec4719e836422c5253a68c1150ac172d8000d/train.py#L331). More advanced aggregation methods should perform better like in other flow-based papers.
